### ISSUE TITLE
Broken?!

### ISSUE THREAD

**Issue by ldexterldesign** [zurb/foundation-icons#49]
Hey,

Call me dumb, but for the life of me I can't get this repo' working?

There seems to be a vast difference between the first SVG file used:
https://github.com/zurb/foundation-icons/blob/f6e73674f2244f6b838db2ebb8464d312f81f148/foundation-icons-general/fonts/foundation-icons-general.svg
... and the latest file:
https://github.com/zurb/foundation-icons/blob/master/foundation_icons_general/fonts/general_foundicons.svg

Do the font files actually exist in the latest Zip?

Cheers,

**Comment by rafibomb** [comment]
Working for us. If you still need help, lets chat on the forum. 

You can also use the CDN
`<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">`
