### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by sochka** [zurb/foundation-icons#51]
All my foundation-icons are showing either as arabic (or some other hieroglyphic language) or blank symbols. I opened index.html from this repo - here is the screenshot. 
![so-q27](https://cloud.githubusercontent.com/assets/822771/5248691/c360b352-7985-11e4-8214-28c483fb993b.png)

**Comment by rafibomb** [comment]
Could be a browser setting issue. The fonts are testing fine here.
